name: parkingusers
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+11

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.20.2 # <-- VERSIÓN ACTUALIZADA
  cached_network_image: ^3.2.3
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.3 # <-- para guardar configuraciones seleccionadas por los usuarios ej el modo oscuro

  # --- PAQUETES DE FIREBASE ---
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2 # <-- para comunicarnos con Firebase Cloud Messaging (FCM)

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/screens/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/map_styles/dark_map_style.json
    - lib/screens/icons/boton_flotante.png
    - lib/screens/icons/icono_menu.png
    - lib/screens/icons/mi_marker.png
    - lib/screens/icons/mi_marker_android.png
    - lib/screens/icons/parkingv2.jpg
    - lib/screens/icons/logoSplash2.png
    - lib/screens/icons/iconMap.png
    - assets/images/
    - lib/screens/icons/MarkMapV.png
    - lib/screens/icons/MarkMapSV.png
    - assets/images/google_logo.png